### ISSUE TITLE
Documentation for rules

### ISSUE THREAD

**Issue by redaxmedia** [Andifeind/docblock#2]
Hey Andi,

thank you for this great library - allready in use for a simple [Grunt task ](https://github.com/redaxmedia/grunt-tocgen) I wrote this week.

I stupled upon the `lib/rules` and wondered what the difference is!? Could you please add some documentation to your `README.md` file?

**Comment by Andifeind** [comment]
Thanks for your comment. I've opened a PR for the documentation. A first drop is already there.
https://github.com/Andifeind/docblock/pull/3

**Comment by redaxmedia** [comment]
I suggest you leave most of the explanation and just focus on a pure API description with code and docblock examples.
